"""add enhanced_url to images

Revision ID: 4528d106da66
Revises: 6d915a81cb51
Create Date: 2026-06-14 10:33:58.397831
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4528d106da66'
down_revision: Union[str, None] = '6d915a81cb51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('enhanced_url', sa.String(length=512), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'enhanced_url')
    # ### end Alembic commands ###
